### ISSUE TITLE
Need aws cli

### ISSUE THREAD

**Issue by jrans** [nikhilaravi/serverless-graphql#5]
Need a note in the read me to make sure people have the [aws-cli](https://aws.amazon.com/cli/) installed

**Comment by nikhilaravi** [comment]
@jrans thanks! Updated the readme!

**Comment by quantuminformation** [comment]
There are quite a few manual steps (like making the bucket and api via bash), I take it sls can't do them by itself?

**Comment by nikhilaravi** [comment]
do you mean the serverless framework?

**Comment by quantuminformation** [comment]
Yeah, thats the one.
